/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package andrew;

import org.junit.Test;
import static org.junit.Assert.*;

public class BoardTest {

    @Test
    public void addPieceSimple() {
        Board b = new Board();
        Piece p = new Piece(Tetromino.Line, 1, b);

        assertTrue(b.addPiece(p));
    }
}
