/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package andrew;

import org.junit.Test;
import static org.junit.Assert.*;

public class PieceTest {
    
    @Test
    public void moveDownSimpleGood() {
        Board b = new Board();
        // Piece p = new Piece();
    }

    @Test
    public void moveDownSimpleBad() {
        Board b = new Board();
        // Piece p = new Piece();
    }
}
